### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by tsing-cv** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#15]
```python
invalid argument
an illegal memory access was encountered
an illegal memory access was encountered
2018-12-04 21:40:24.309568: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:649] failed to record completion event; therefore, failed to create inter-stream dependency
2018-12-04 21:40:24.309604: I tensorflow/stream_executor/stream.cc:4792] stream 0x56500d584e70 did not memcpy host-to-device; source: 0x7f6415388040
2018-12-04 21:40:24.309618: E tensorflow/stream_executor/stream.cc:317] Error recording event in stream: error recording CUDA event on stream 0x56500d584f10: CUDA_ERROR_ILLEGAL_ADDRESS; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2018-12-04 21:40:24.309633: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
2018-12-04 21:40:24.309643: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:206] Unexpected Event status: 1
Aborted (core dumped)
```
@yangxue0827 @yangJirui

**Comment by issuetodd** [comment]
After i changed all the same environment as in Readme and i don't have this kinds of problems. 
Maybe you can check your cuda version and environment first.

**Comment by tsing-cv** [comment]
solved!

**Comment by XWalways** [comment]
I've checked my tensorflow=1.2.1，cuda=8.0.61，cudnn=5.1，python=2.7，but always out of memory,WHY ?

**Comment by JJJackssson** [comment]
@tsing-cv hello, i meet the problem,too.can you give me some help

**Comment by jxingm** [comment]
> solved!

Hi,can you share your environment versions with me?I have met the same problem and changing environment doesn't help.Thanks!

**Comment by JJJackssson** [comment]
@jxingm just simply the structure of the network (such as the number of anchors). it works for me.
